import * as XLSX from 'xlsx'
import type { Receipt, ActivityLogEntry } from '../types'

function footerText(): string {
  const now = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })
  return `Generated by HuskyTrack on ${now}`
}

// Appends a blank row plus the footer below the table without expanding the
// autofilter range onto it -- the autofilter ref is captured from the sheet
// BEFORE the footer rows are added, since sheet_add_aoa grows `!ref` to
// cover whatever it appends.
function addFooter(ws: XLSX.WorkSheet): void {
  const dataRef = ws['!ref'] as string
  XLSX.utils.sheet_add_aoa(ws, [[], [footerText()]], { origin: -1 })
  ws['!autofilter'] = { ref: dataRef }
}

export function generateXlsx(receipts: Receipt[]): Uint8Array {
  const data = receipts.map((r) => ({
    Date:           r.date,
    Merchant:       r.merchant,
    Amount:         r.amount,
    Category:       r.category,
    Purpose:        r.purpose_sub ?? r.purpose ?? '',
    City:           r.city ?? '',
    State:          r.state ?? '',
    Card:           r.card_name ?? (r.card_last_four ? `••••${r.card_last_four}` : ''),
    'Qualified?':   r.is_qualified ? 'Yes' : 'No',
    'Created At':   r.created_at,
  }))

  const ws = XLSX.utils.json_to_sheet(data)

  // Column widths
  ws['!cols'] = [
    { wch: 12 }, // Date
    { wch: 28 }, // Merchant
    { wch: 10 }, // Amount
    { wch: 24 }, // Category
    { wch: 22 }, // Purpose
    { wch: 18 }, // City
    { wch: 8 },  // State
    { wch: 20 }, // Card
    { wch: 10 }, // Qualified
    { wch: 22 }, // Created At
  ]
  // Adds the header-row filter dropdowns Excel/Sheets show for "filterable" data.
  ws['!autofilter'] = { ref: ws['!ref'] as string }
  addFooter(ws)

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Expenses')

  return new Uint8Array(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer)
}

export function generateActivityLogXlsx(entries: ActivityLogEntry[]): Uint8Array {
  const data = entries.map((e) => ({
    'Added At':    e.created_at,
    Source:        e.source,
    Merchant:      e.merchant,
    Amount:        e.amount,
    'Expense Date': e.date,
    Category:      e.category,
    City:          e.city ?? '',
    State:         e.state ?? '',
  }))

  const ws = XLSX.utils.json_to_sheet(data)

  ws['!cols'] = [
    { wch: 22 }, // Added At
    { wch: 18 }, // Source
    { wch: 28 }, // Merchant
    { wch: 10 }, // Amount
    { wch: 14 }, // Expense Date
    { wch: 24 }, // Category
    { wch: 18 }, // City
    { wch: 8 },  // State
  ]
  ws['!autofilter'] = { ref: ws['!ref'] as string }
  addFooter(ws)

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Activity Log')

  return new Uint8Array(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer)
}
