import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Receipt, ReportSummary, CategorySummary, ExpenseCategory } from '../types';

function fmt(n: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
}

function buildHtml(summary: ReportSummary, receipts: Receipt[], name: string): string {
  const year = summary.start_date.slice(0, 4) || new Date().getFullYear().toString();

  const categoryRows = summary.by_category
    .map(
      (c) => `
      <tr>
        <td>${c.category}</td>
        <td style="text-align:center">${c.count}</td>
        <td style="text-align:right">${fmt(c.total)}</td>
        <td style="text-align:center;color:${c.is_qualified ? '#10b981' : '#ef4444'}">
          ${c.is_qualified ? '✓ Qualified' : '✗ Not Qualified'}
        </td>
      </tr>`,
    )
    .join('');

  const receiptRows = receipts
    .map(
      (r) => `
      <tr>
        <td>${r.date}</td>
        <td>${r.merchant}</td>
        <td style="text-align:right">${fmt(r.amount)}</td>
        <td>${r.category}</td>
        <td>${r.purpose ?? '—'}</td>
        <td style="text-align:center">${r.card_last_four ? `····${r.card_last_four}` : '—'}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  * { font-family: -apple-system, Helvetica, sans-serif; margin: 0; padding: 0; box-sizing: border-box; }
  body { color: #111827; font-size: 11px; padding: 40px; }
  h1 { font-size: 28px; color: #1a56db; font-weight: 800; }
  h2 { font-size: 16px; color: #1a56db; margin: 28px 0 10px; border-bottom: 2px solid #1a56db; padding-bottom: 4px; }
  .meta { margin: 16px 0 8px; line-height: 1.8; }
  .meta span { font-weight: 600; }
  .totals { display: flex; gap: 24px; margin: 20px 0; }
  .total-box { flex: 1; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px; }
  .total-box .label { font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
  .total-box .value { font-size: 22px; font-weight: 800; margin-top: 4px; }
  .qualified .value { color: #10b981; }
  .nonqualified .value { color: #f59e0b; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { background: #1a56db; color: #fff; padding: 8px 6px; text-align: left; font-size: 10px; letter-spacing: 0.3px; }
  td { padding: 7px 6px; border-bottom: 1px solid #f3f4f6; }
  tr:last-child td { border-bottom: none; }
  tr:nth-child(even) { background: #f9fafb; }
  .footer { margin-top: 40px; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style>
</head>
<body>

<h1>EduTrack</h1>
<div style="font-size:14px;color:#6b7280;margin-top:2px">529 Qualified Education Expense Report</div>

<div class="meta">
  <div><span>Account Holder:</span> ${name}</div>
  <div><span>Tax Year:</span> ${year}</div>
  <div><span>Period:</span> ${summary.start_date || 'All time'} – ${summary.end_date || 'Present'}</div>
  <div><span>Generated:</span> ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</div>
</div>

<div class="totals">
  <div class="total-box qualified">
    <div class="label">Total Qualified Expenses</div>
    <div class="value">${fmt(summary.total_qualified)}</div>
  </div>
  <div class="total-box nonqualified">
    <div class="label">Non-Qualified</div>
    <div class="value">${fmt(summary.total_non_qualified)}</div>
  </div>
</div>

<h2>Category Summary</h2>
<table>
  <thead><tr><th>Category</th><th style="text-align:center">Transactions</th><th style="text-align:right">Total</th><th style="text-align:center">Status</th></tr></thead>
  <tbody>${categoryRows}</tbody>
</table>

<h2>Itemized Expenses</h2>
<table>
  <thead><tr><th>Date</th><th>Merchant</th><th style="text-align:right">Amount</th><th>Category</th><th>Purpose</th><th style="text-align:center">Card</th></tr></thead>
  <tbody>${receiptRows}</tbody>
</table>

<div class="footer">
  This report is generated by EduTrack for informational purposes only. Consult a qualified tax professional
  to verify 529 qualified expense eligibility. Retain all original receipts for your records.
  Total records: ${receipts.length}.
</div>

</body>
</html>`;
}

export async function exportPdf(
  summary: ReportSummary,
  receipts: Receipt[],
  accountName: string,
): Promise<void> {
  const html = buildHtml(summary, receipts, accountName);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Save or Share EduTrack Report',
  });
}
